repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.1
    hooks:
      - id: pyupgrade
        language_version: python3.7
  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        language_version: python3.7
  - repo: https://github.com/python/black
    rev: 21.5b2
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-docstrings,
          flake8-builtins,
          flake8-comprehensions,
          flake8-print,
          flake8-eradicate,
        ]
        language_version: python3.7
