name: download dependencies

on: [push]
jobs:
  download-linux-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download dependencies
        run: |
          python -m pip install pip -U
          pip download -r src/requirements.txt -d dependencies
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-dependencies
          path: |
            dependencies
  download-windows-dependencies:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [ "3.7", "3.10" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download dependencies
        run: |
          python -m pip install pip -U
          pip download -r src/requirements.txt -d dependencies
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-dependencies
          path: |
            dependencies
